spring:
  application:
    name: greeting-service
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    config:
      import-check:
        enabled: false
  greeting-service:
    greeting: Olá
  default-value: Mundo